export const surpriseMePrompts = [
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "An armchair in the shape of an avocado",
  "An expressive oil painting of a basketball player dunking, depicted as an explosion of a nebula",
  "A photo of a white fur monster standing in a purple room",
  "A 3D render of an astronaut walking in a green desert",
  "A futuristic neon lit cyborg face",
  "A bowl of soup that is also a portal to another dimension, digital art",
  "A van Gogh style painting of an American football player",
  "'A sea otter with a pearl earring' by Johannes Vermeer",
  "An abstract painting of artificial intelligence",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "An Andy Warhol style painting of a french bulldog wearing sunglasses",
  "A cyberpunk monster in a control room",
  "A photo of a white fur monster standing in a purple room",
  "Painting art dog scientist teaching humans",
  "dog on the moon and eating pizza”",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
];
