export const surpriseMePrompts = [
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "An armchair in the shape of an avocado",
  "An expressive oil painting of a basketball player dunking, depicted as an explosion of a nebula",
  "A photo of a white fur monster standing in a purple room",
  "A 3D render of an astronaut walking in a green desert",
  "A futuristic neon lit cyborg face",
  "A bowl of soup that is also a portal to another dimension, digital art",
  "A van Gogh style painting of an American football player",
  "'A sea otter with a pearl earring' by Johannes Vermeer",
  "An abstract painting of artificial intelligence",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "An Andy Warhol style painting of a french bulldog wearing sunglasses",
  "A cyberpunk monster in a control room",
  "A photo of a white fur monster standing in a purple room",
  "Painting art dog scientist teaching humans",
  "dog on the moon and eating pizza”",
];
