import React from "react";
import { Card, Loader, FormField } from "../components";
import { Box, Flex, Grid, Heading, Text } from "@chakra-ui/react";
import { useState } from "react";

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post.id} {...post} />);
  }

  return (
    <Heading as="h2" size="md" textTransform="uppercase" mt="5" color="#6449ff">
      {title}
    </Heading>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPost, setAllPost] = useState(null);
  const [searchText, setSearchText] = useState(false);
  return (
    <Box maxW="7xl">
      <Box>
        <Heading fontWeight="600" as="h1" color="#222328" fontSize="32px">
          The Community Showcase
        </Heading>
        <Text mt="2" color="#666e75" fontSize="14px" maxW="500px">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </Text>
      </Box>
      <Box mt="16">
        <FormField />
      </Box>

      <Box mt="10">
        {loading ? (
          <Flex justifyContent="center" alignItems="center">
            <Loader />
          </Flex>
        ) : (
          <>
            {searchText && (
              <Heading size="md" as="h2" color="#666e75" mb="3">
                showing results for
              </Heading>
            )}

            <Grid
              templateColumns={{
                lg: "repeat(4, 1fr)",
                md: "repeat(3, 1fr)",
                xs: "repeat(2, 1fr)",
                base: "repeat(1, 1fr)",
              }}
              gap={3}
            >
              {searchText ? (
                <RenderCards data={[]} title="No Search result found" />
              ) : (
                <RenderCards data={[]} title="No posts found" />
              )}
            </Grid>
          </>
        )}
      </Box>
    </Box>
  );
};

export default Home;
